
title: DeepMeteo
page-top-title: DeepMeteo
top-section-bg-text: Advanced Atmospheric Modeling & Monitoring Group
# home-subtitle: INTRODUCTION
copyright-text: '&copy; 2023 <u><a href="https://github.com/senli1073/senli1073.github.io">DeepMeteo</a></u>'
