
title: DeepMeteo
page-top-title: DeepMeteo
top-section-bg-text: Advanced Earth & Atmosphere Modeling & Monitoring Group
home-subtitle: Introduction
copyright-text: '&copy; <u><a href="https://github.com/senli1073/senli1073.github.io">Sen Li</a></u> 2023. All Rights Reserved.'
